# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c5494db8c28c80a7f3aa999d1f32aebe2f3761d8ec8271fba3addd9abe0f99c0fdf1238985c8d717141be3ac2dc2b25abaee65d6fc8f25de69a35dd2d9c079

test:
  secret_key_base: 1aa720822ee4e6c0a7800e70a56838619948c21f6ee5e7d97382982592a447336b0e6e952754f5bbf4b6d31b8b689f95ab570f041a84d70045898409e5d4e4b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
